name: push new package

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: ultimate
        if: false
        shell: powershell
        run: |
          cd ultimate
          choco pack
          choco push --source https://push.chocolatey.org/ -k $env:CHOCO_KEY
        env:
          CHOCO_KEY: ${{ secrets.CHOCO_KEY }}
      - name: community
        if: false
        shell: powershell
        run: |
          cd community
          choco pack
          choco push --source https://push.chocolatey.org/ -k $env:CHOCO_KEY
        env:
          CHOCO_KEY: ${{ secrets.CHOCO_KEY }}
      - name: unified
        shell: powershell
        run: |
          cd unified
          choco pack
          choco push --source https://push.chocolatey.org/ -k $env:CHOCO_KEY
        env:
          CHOCO_KEY: ${{ secrets.CHOCO_KEY }}
